export default {
  translation: {
    Story: "Story",
    Settings: "Settings",
    Followers: "Followers",
    Following: "Following",
    Events: "Events",
    Members: "Members",
    All: "All",
    Week: "Week",
    Month: "Month",
    Search: "Search",
    Profiles: "Profiles",
    Organizations: "Organizations",
    No_user: "No user found",
    No_organization: "No organization found",
    First_name: "First name",
    Last_name: "Last name",
    Email: "Email",
    Password: "Password",
    Delete: "delete",

    login: {
      social_network: "All you need in one place to find, create and manage events & communities",
      signin: "Sign in",
      login: "Log in",
      welcome: "Welcome to WeShre!",
      signin_account: "Sign in to your account",
      authenticating: "Authenticating...",
      signin_email: "Sign in with email",
      signin_google: "Sign in with Google",
      account: "Don't have an account?",
      signup: "Sign up",
      create_account: "Create your account",
      sign_join: "Sign up to join WeShre",
      privacy: "I accept terms of service and privacy policy",
      already: "Already have an account?",
      creating: "Creating Account...",
      add_infos: "Add your info for a better experience",
      add_picture: "Add a picture profile",
      gender: "Gender",
      male: "Male",
      female: "Female",
      other: "Other",
      birthdate: "Birthdate",
      select_picture: "Please select a picture (jpg, png, gif, etc.)",
      picture_exceed: "Picture should not exceed ",
      update_profile: "Updating Profile",
      connect: "Connect",
      fill_all: "Fill all the fields",
    },

    nav: {
      home: "Home",
      search: "Search",
      events: "Events",
      chats: "Chats",
      community: "Community/Group",
      create: "Create",
      switch: "Switch account",
      settings: "Settings",
      logout: "Log out",
    },

    settings: {
      details: "My details",
      languages: "Languages",
      payout: "Payout settings",
      privacy: "Privacy settings",
      subscription: "Subscription",
      invite: "Invite friends",
      membership: "My membership",
      marketplace: "Marketplace",
      info: "App info",
      theme: "Theme",
    },

    homepage: {
      suggestion: "Our suggestion for you",
      explore: "Explore",
      foryou: "For you",
      following: "Following",
      news: "News",
    },

    header: {
      brussels: "Brussels",
      search: "Search",
      filters: "Filters",
      create: "Create an event",
      map: "Map",
      notifications: "Notifications",
    },

    details: {
      chat: "Open chat",
      creator: "Created by",
      datetime: "Date and Time",
      map: "Map",
      guests: "Guests",
      tickets: "Tickets",
      about: "About this event",
      included: "What's included",
      drinks: "Drinks",
      food: "Food",
      participate: "Participate",
      free: "Free",
      download_ticket: "Download ticket",
      address: "Address",
      description: "Description",
    },

    ticket: {
      ticket: "Ticket",
      tickets: "Tickets",
      order: "Order",
      price: "Price",
      soldOut: "Sold out",
      unlimited: "Unlimited",
      fee: "Service fee",
      addOwner: "Add ticket owner",
      removeOwner: "Remove ticket owner",
      addTicket: "Add ticket",
      removeTicket: "Remove ticket",
      availableFrom: "Available from",
      availableUntil: "Available until",
      salesClosed: "Sales closed",
      orderSummary: "Order summary",
      userVisibilityDescription: "{{name}} is a user who can buy this ticket",
      organizationVisibilityDescription: "You are part of the {{name}} organization whose members can buy this ticket",
      membershipVisibilityDescription: "You have the {{name}} card whose members can buy this ticket",
      ticketOwnerRestriction: "This ticket has restricted access, so you can't invite anyone from outside the application.",
      ticketRestrictionAccess: "This person does not have access to this ticket.",
      ticketAlreadyAdded: "This person has already been added or already has a ticket.",
    },

    search: {
      search: "Search",
      activities: "Activities",
      profiles: "Profiles",
      organizations: "Organizations",
      noresult: "No result",
    },

    feeds: {
      ticket: "Ticket",
      chat: "Chat",
      guests: "Guests",
      sharedAlbum: "Shared Album",
      form: "Form",
    },

    event: {
      myEvents: "My Events",
      filter_message: "Please be patient, this filter is not fully functional yet.",
      filter_message2: "All events since I joined WeShre",
    },

    my_details: {
      my_details: "My Details",
      account_details: "Account details",
      profile_picture: "Profile picture",
      display: "Display name",
      city: "City",
      first_name: "First name",
      last_name: "Last name",
      description: "Add a description",
      birthdate: "Birthdate",
      school: "School",
    },

    profiles: {
      follow: "Follow",
      message: "Message",
      about: "About",
      my_activities: "My activities",
      participated: "Participated",
      coming: "Coming events",
      past: "Past events",
      photos: "Photos",
      info: "General Infos",
      events: "Events",
    },

    404: {
      error: "Page not found",
      p1: "It seems that the page you are trying to reach does not exist.",
      p2: "The web version of WeShre is under development, for a more complete experience we invite you to download the mobile application on Android and iOS.",
    },
  },
};
