export default {
  translation: {
    Story: "Story",
    Settings: "Paramètres",
    Followers: "Abonnés",
    Following: "Suivis",
    Events: "Événements",
    Members: "Membres",
    All: "Tous",
    Week: "Semaine",
    Month: "Mois",
    Search: "Recherche",
    Profiles: "Profils",
    Organizations: "Organisations",
    No_user: "Aucun utilisateur trouvé",
    No_organization: "Aucune organisation trouvée",
    First_name: "Prénom",
    Last_name: "Nom",
    Email: "Email",
    Password: "Mot de passe",
    Delete: "supprimer",

    login: {
      social_network: "Tout ce dont vous avez besoin au même endroit, créez et organisez vos événements & communautés",
      signin: "Connexion",
      login: "Connexion",
      welcome: "Bienvenue sur WeShre!",
      signin_account: "Connectez-vous à votre compte",
      authenticating: "Authentification...",
      signin_email: "Connexion avec email",
      signin_google: "Connexion avec Google",
      account: "Pas de encore de compte?",
      signup: "Créez votre compte",
      create_account: "Création de votre compte",
      sign_join: "Inscrivez-vous et rejoignez WeShre",
      privacy: "J'accepte les termes du service et la politique de confidentialité",
      already: "Vous avez déjà un compte ?",
      creating: "Création du compte...",
      add_infos: "Ajoutez vos informations pour une meilleure expérience",
      add_picture: "Ajoutez une photo de profil",
      gender: "Genre",
      male: "Homme",
      female: "Femme",
      other: "Autre",
      birthdate: "Date de naissance",
      select_picture: "Sélectionnez une photo svp (jpg, png, gif, etc.)",
      picture_exceed: "L'image ne doit pas dépasser ",
      update_profile: "Mise à jour du profil",
      connect: "Connexion",
      fill_all: "Remplissez tous les champs",
    },

    nav: {
      home: "Accueil",
      search: "Rechercher",
      events: "Événements",
      chats: "Discussions",
      community: "Communauté/Groupe",
      create: "Créer",
      switch: "Changer de compte",
      settings: "Paramètres",
      logout: "Se déconnecter",
    },

    settings: {
      details: "Mes informations",
      languages: "Langues",
      payout: "Paramètres de paiement",
      privacy: "Paramètres de confidentialité",
      subscription: "Abonnements",
      invite: "Inviter des amis",
      membership: "Mes adhésions",
      marketplace: "Marketplace",
      info: "Informations sur l'application",
      theme: "Thème",
    },

    homepage: {
      suggestion: "Nos suggestions pour vous",
      explore: "Explorer",
      foryou: "Pour vous",
      following: "Abonnements",
      news: "Nouveautés",
    },

    header: {
      brussels: "Bruxelles",
      search: "Rechercher",
      filters: "Filtres",
      create: "Créer un événements",
      map: "Carte",
      notifications: "Notifications",
    },

    details: {
      chat: "Ouvrir une discussion",
      creator: "Créé par",
      datetime: "Date et heure",
      map: "Carte",
      guests: "Invités",
      tickets: "Tickets",
      about: "À propos de cet événement",
      included: "Inclus",
      drinks: "Boissons",
      food: "Nourriture",
      participate: "Participer",
      free: "Gratuit",
      download_ticket: "Télécharger ticket",
      address: "Adresse",
      description: "Description",
    },

    ticket: {
      ticket: "Ticket",
      tickets: "Tickets",
      order: "Commandé",
      price: "Prix",
      soldOut: "Épuisé",
      unlimited: "Illimité",
      fee: "Frais de service",
      addOwner: "Ajouter un propriétaire de ticket",
      removeOwner: "Supprimer le propriétaire du ticket",
      addTicket: "Ajouter un ticket",
      removeTicket: "Supprimer le ticket",
      availableFrom: "Disponible à partir du",
      availableUntil: "Disponible jusqu'au",
      salesClosed: "Vente terminée",
      orderSummary: "Résumé de la commande",
      userVisibilityDescription: "{{name}} fait partie des utilisateurs qui peuvent acheter ce ticket",
      organizationVisibilityDescription: "Vous faites partie de l'organization {{name}} dont les membres qui peuvent acheter ce ticket",
      membershipVisibilityDescription: "Vous possédez la carte {{name}} dont les membres peuvent acheter ce ticket",
      ticketOwnerRestriction: "Ce ticket a un accès restreint, vous ne pouvez donc pas inviter une personne en dehors de l'application.",
      ticketRestrictionAccess: "Cette personne n'a pas accès à ce ticket.",
      ticketAlreadyAdded: "Cette personne est déjà ajoutée ou possède déjà un ticket.",
    },

    search: {
      search: "Recherche",
      activities: "Activités",
      profiles: "Profils",
      organizations: "Organisations",
      noresult: "Aucun résultat",
    },

    feeds: {
      ticket: "Ticket",
      chat: "Chat",
      guests: "Participants",
      sharedAlbum: "Album partagé",
      form: "Formulaire",
    },

    event: {
      myEvents: "Mes événements",
      filter_message: "Ce filtre ne fonctionne pas encore, mais ça viendra",
      filter_message2: "Tous mes événements depuis que j'ai rejoint WeShre",
    },

    my_details: {
      my_details: "Mes informations",
      account_details: "Informations du compte",
      profile_picture: "Photo de profil",
      display: "Nom d'affichage",
      city: "Ville",
      first_name: "Prénom",
      last_name: "Nom",
      description: "Ajouter une description",
      birthdate: "Date de naissance",
      school: "École",
    },

    profiles: {
      follow: "Suivre",
      message: "Message",
      about: "À propos",
      my_activities: "Mes activités",
      participated: "Participations",
      coming: "Événements à venir",
      past: "Événements passés",
      photos: "Photos",
      info: "Informations générales",
      events: "Événements",
    },

    404: {
      error: "Page non disponible",
      p1: "Il semblerait que la page que vous essayez d'atteindre n'existe pas.",
      p2: "La version web de WeShre est en cours de création, pour une expérience plus complète nous vous invitons à télécharger l'application' mobile sur Android et iOS.",
    },
  },
};
